# model/tokenizer
model_name: "zpn/llama-7b"
tokenizer_name: "zpn/llama-7b"
gradient_checkpointing: false
save_name: "zpn/vicuna-lora"

# dataset
streaming: false
num_proc: 64
dataset_path: "data"
max_length: 1024
batch_size: 4

# train dynamics
lr: 5.0e-5
eval_every: 2000
eval_steps: 100
save_every: 2000
output_dir: "ckpts/llama-7b"
checkpoint: null
lora: true
warmup_steps: 100

# logging
wandb: true
wandb_entity: vicuna
wandb_project_name: vicuna
seed: 42