# model/tokenizer
model_name: "EleutherAI/gpt-j-6B"
tokenizer_name: "EleutherAI/gpt-j-6B"
gradient_checkpointing: true
save_name: "nomic-ai/gpt4all-gptj-multiturn-lr-aggressive"

# dataset
streaming: false
num_proc: 64
dataset_path: "data_multiplus" 
max_length: 1024
batch_size: 8

# train dynamics
lr: 2.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 200
eval_steps: 105
save_every: 400
log_grads_every: 200
output_dir: "ckpts/gpt4all-gptj-full-multiturn-lr-aggreive"
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 4 

# logging
wandb: true
wandb_entity: vicuna
wandb_project_name: vicuna
seed: 42

